- name: Morning Challenge
  hosts: renamed,!taz
  connection: ssh
  gather_facts: no

  vars:
      user_me: rshriner

  tasks:
      - name: Create new user group
        ansible.builtin.group:
          name: funkytown
        become: yes
      - name: Create new user
        ansible.builtin.user:
          name: "{{ user_me}}"
          groups: funkytown
        become: yes
