---
- name: Playbook - Install figlet
  hosts: planetexpress
  gather_facts: yes   # default is yes

  tasks:
  - name: using apt to remove figlet
    apt:
        name: figlet
        state: absent    # this will REMOVE the application
    become: yes

